<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 * @var $escaper \Magento\Framework\Escaper
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('large_image_url') :
    $helper->getDefaultPlaceholderUrl('image');
    $imageWidth = $block->getImageAttribute('product_page_image_medium', 'width');
    $imageHeight = $block->getImageAttribute('product_page_image_medium', 'height');

?>

<div class="products-gallery-images owl-carousel owl-theme">
    <div class="item">
        <img
            alt="main product photo"
            class=""
            src="<?= /* @noEscape */ $mainImageData ?>"
            <?= $imageWidth ? 'width="'. $escaper->escapeHtmlAttr($imageWidth) .'"' : '' ?>
            <?= $imageHeight ? 'height="'. $escaper->escapeHtmlAttr($imageHeight) .'"' : '' ?>
        />
    </div>
    <?php if(!empty($images)) {
        foreach ($images as $productsImages) {
            if ($productsImages->getData('position') > 0) { ?>
                <div class="item">
                    <img
                        alt="main product photo"
                        class=""
                        src="<?= /* @noEscape */ $productsImages->getData('large_image_url') ?>"
                        <?= $imageWidth ? 'width="'. $escaper->escapeHtmlAttr($imageWidth) .'"' : '' ?>
                        <?= $imageHeight ? 'height="'. $escaper->escapeHtmlAttr($imageHeight) .'"' : '' ?>
                    />
                </div>
           <?php }
        }
    }
    ?>
</div>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
